# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr:
- '*'
trigger:
- main

jobs:
  # Run Infracost on pull requests
  - job: infracost_pull_request_checks
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Run Infracost on pull requests
    pool:
      vmImage: ubuntu-latest
      permissions:
      #   contents: read
      #   pull-requests: write  

    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0
    - task: InfracostSetup@2
      inputs:
        # serviceConnection: 'githubPR'
        apiKey: 'ico-0LLqDR3ojP26GDGA1ShYcCTOEMiOHrrk'
        version: '0.10.34'

    - script: |
        echo TESTTTTT===== $(System.PullRequest.TargetBranchName)
        git clone $(Build.Repository.Uri) --branch=main --single-branch /tmp/base
      displayName: Checkout base branch

    # Generate an Infracost cost estimate baseline from the comparison branch, so that Infracost can compare the cost difference.
    - bash: |
        ls
        cat /tmp/infracost-base.json
        pwd
        cd /tmp/base
        infracost breakdown --path . \
          --format=json \
          --out-file=/tmp/infracost-base.json
      displayName: Generate Infracost cost estimate baseline

    # Generate an Infracost diff and save it to a JSON file..
    - bash: |
        cd -
        pwd
        infracost diff --path . --compare-to /tmp/infracost-base.json --out-file /tmp/infracost.json
        # infracost diff --path=. \
        #   --format=json \
        #   --compare-to=/tmp/infracost-base.json \
        #   --out-file=/tmp/infracost.json
        ls /tmp
      displayName: Generate Infracost diff
    
    # Add a cost estimate comment to a Azure Repos pull request..
    # - script: |
    #     echo prnmbr=$(System.PullRequest.PullRequestId)
    #     echo prnmbr=$(System.PullRequest.PullRequestNumber)
    #     # echo repo=$(Build.Repository.Uri)
    #     # echo commitid=$BUILD_SOURCEVERSION
    #     git config --global user.email "myemail@someOrganization.com" && git config --global user.name "John Doe"
    #     ls /tmp
    #     infracost comment github \
    #       --path=/tmp/infracost-base.json \
    #       --pull-request=$(System.PullRequest.PullRequestNumber) \
    #       --repo=$(Build.Repository.Uri) \
    #       --github-token=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 \
    #       --behavior=update
    #   displayName: Post PR comment
      # env:
      #   GitHubServiceConnection: 'github.com_rinshad1'

    - bash: |
        cat="/tmp/infracost-base.json"
        commentfile = $(cat="/tmp/infracost-base.json")
        # body=$(cat $comment_file)
        # endpoint="https://api.github.com/repos/$(Build.Repository.Name)/issues/$(System.PullRequest.PullRequestId)/comments"
        # curl -X POST -H "Authorization: token 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" -d "{\"body\": \"$body\"}" $endpoint
      displayName: 'Post Comment from File in GitHub PR'
      


    - task: GitHubComment@0
      inputs:
        gitHubConnection: 'github.com_rinshad1'
        repositoryName: '$(Build.Repository.Name)'
        comment: $commentfile
      env:
        commentfile: $(cat="/tmp/infracost-base.json")