trigger:
- main  # Change this to your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0
- script: |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    # git remote set-url origin https://github.com/rinshad1/eks_cluster_module.git
    # git fetch
    git config --global credential.helper "!f() { echo "username=`rinshad1`npassword=`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`"; }; f"
    git checkout $(Build.SourceBranchName)
    # git clone https://github.com/rinshad1/eks_cluster_module.git
    ls
    cd eks_cluster_module
    ls
    # Make changes to files 
    echo "This Is Build $(Build.BuildId)" >> README.md
    cat README.md
    git add .
    git commit -m "Commit message from azure pipeline"
    git push origin main
  displayName: 'Commit and Push to GitHub'
